---
title: "6. Station"
toc: false
sidebar: false
---
Ihr habt das Blindlaufen überstanden! Könnt ihr euch vorstellen die ganze Zeit Blind zu sein? Vielleicht gibt es hier ein Eis? Diese Aufgabe lässt sich auch im Sitzen erledigen. 

### Wie geht es zur nächsten Station?
::: {.panel-tabset}

## Aufgabe
Kann einer der Erwachsenen die Geschichte vom hässlichen Entlein erzählen? Finden die Kinder eine Brutstätte eines Schwans?  

## Das Märchen

### Das häßliche junge Entlein.

Es war herrlich draußen auf dem Lande; es war Sommer, das Korn stand gelb, der Hafer grün, das Heu war unten auf den grünen Wiesen in Schobern aufgesetzt, und da ging der Storch auf seinen langen roten Beinen und plapperte ägyptisch, denn diese Sprache hatte er von seiner Mutter gelernt. Rings um den Acker und die Wiese waren große Wälder und mitten in den Wäldern tiefe Seen, ja es war wirklich herrlich da draußen auf dem Lande! Mitten im Sonnenschein lag dort ein altes Rittergut, von tiefen Kanälen umgeben, und von der Mauer bis zum Wasser herunter wuchsen große Klettenblätter, die so hoch waren, daß kleine Kinder unter den höchsten aufrecht stehen konnten; es war aber so wild darin, wie im tiefsten Walde. Hier saß eine Ente auf dem Neste, welche ihre Jungen ausbrüten mußte, aber es wurde ihr fast zu langweilig, ehe die Jungen kamen, dazu bekam sie selten Besuch; die andern Enten schwammen lieber in den Kanälen umher, als daß sie hinauf liefen, sich unter ein Kleeblatt zu setzen und mit ihr zu schnattern.

Endlich borst ein Ei nach dem andern. »Piep, piep!« sagte es und alle Eidotter waren lebendig geworden und die jungen Entlein steckten den Kopf her aus.[97]

»Rapp, rapp!« sagte sie, und so rappelten sich alle, was sie konnten, und sahen nach allen Seiten unter den grünen Blättern, und die Mutter ließ sie sehen, so viel sie wollten, denn das Grüne ist gut für die Augen.

»Wie groß ist doch die Welt!« sagten alle Jungen; denn nun hatten sie freilich ganz anders Platz, als wie sie noch drinnen im Ei lagen.

»Glaubt Ihr, daß dies die ganze Welt sei?« sagte die Mutter. »Die erstreckt sich noch weit über die andere Seite des Gartens, gerade hinein in des Pfarrers Feld, aber da bin ich noch nie gewesen! Ihr seid doch alle beisammen?« fuhr sie fort, und so stand sie auf. »Nein, ich habe noch nicht alle, das größte Ei liegt noch da. Wie lange soll das noch währen? Jetzt bin ich es bald überdrüssig!« Und so setzte sie sich wieder.

»Nun, wie geht es?« sagte eine alte Ente, welche gekommen war, um ihr einen Besuch abzustatten.

»Es währt so lange mit dem einen Ei!« sagte die Ente, die da saß; »es will nicht entzwei gehen; doch blicke nur auf die andern hin, sind sie nicht die niedlichsten Entlein, die man je gesehen? Sie gleichen allesamt ihrem Vater; der Bösewicht kommt nicht, mich zu besuchen.«

»Laß mich das Ei sehen, welches nicht bersten will!« sagte die Alte. »Glaube mir, es ist ein Kalekutenei; ich bin auch einmal so angeführt worden, und hatte meine große Sorge und Not mit den Jungen, denn ihnen ist bange vor dem Wasser. Ich konnte sie nicht hinein bekommen, ich rappte und schnappte, aber es half nichts. Laß mich das Ei sehen. Ja, das ist ein Kalekutenei, laß Du das liegen und lehre lieber die andern Kinder schwimmen.«

»Ich will doch noch ein bißchen darauf sitzen,« sagte die Ente, »habe ich nun so lange gesessen, kann ich auch noch einige Zeit sitzen.«

»Nach Belieben,« sagte die alte Ente und ging von dannen.

Endlich borst das große Ei. »Piep, piep!« sagte das[98] Junge und kroch heraus; es war groß und häßlich. Die Ente betrachtete es. »Das ist doch ein gewaltig großes Entlein,« sagte sie; »keins von den andern sieht so aus; sollte es doch ein kalekutisches Küchlein sein? Nun, wir wollen bald dahinter kommen; in das Wasser muß es, ob ich es auch selbst hineinstoßen soll.«

Am nächsten Tage war schönes, herrliches Wetter. Die Sonne schien auf all' die grünen Kletten. Die Entleinmutter ging mit ihrer ganzen Familie zu dem Kanal hinunter; platsch; da sprang sie in das Wasser. »Rapp, rapp!« sagte sie, und ein Entlein nach dem andern plumpte hinein; das Wasser schlug ihnen über dem Kopfe zusammen, aber sie kamen gleich wieder empor und schwammen so prächtig, die Beine gingen von selbst, und alle waren sie darin, selbst das häßliche, graue Junge schwamm mit.

»Nein, es ist kein Kalekut,« sagte sie; »sieh, wie herrlich es die Beine gebraucht, wie gerade es sich hält, es ist mein eigenes Kind. Im grunde ist es doch ganz hübsch, wenn man es nur recht betrachtet. Rapp, rapp! – Kommt nur mit mir, ich werde Euch in die große Welt führen, Euch im Entenhof vorstellen, aber haltet Euch immer nahe zu mir, damit niemand auf Euch trete, und nehmt Euch vor den Katzen in acht!«

Und so kamen sie in den Entenhof hinein. Da drinnen war ein schrecklicher Lärm, denn da waren zwei Familien, die sich um einen Aalkopf bissen, und am Ende bekam ihn doch die Katze.

»Seht, so geht es in der Welt zu!« sagte die Entenmutter und wetzte ihren Schnabel, denn sie wollte auch den Aalkopf haben. »Braucht nur die Beine!« sagte sie. »Seht, daß Ihr Euch rappeln könnt, und neigt Euren Hals vor der alten Ente dort; sie ist die vornehmste von allen hier; sie ist aus spanischem Geblüt, deswegen ist sie so dick; und seht Ihr, sie hat einen roten Lappen um das Bein, das ist etwas außerordentlich Schönes und die größte Auszeichnung, welche einer Ente zu Teil[99] werden kann; das bedeutet so viel, daß man sie nicht verlieren will und daß sie von Tier und Menschen erkannt werden soll! Rappelt Euch; setzt die Füße nicht einwärts. Ein wohlerzogenes Entlein setzt die Füße weit von einander, gerade wie Vater und Mutter; seht, so! Nun neigt Euren Hals und sagt: ›Rapp!‹«

Und das thaten sie; aber die anderen Enten ringsumher betrachteten sie und sagten ganz laut: »Sieh da! Nun sollen wir noch den Anhang haben, als ob wir nicht schon genug wären, und pfui! wie das eine Entlein aussieht, das wollen wir nicht dulden!« Und sogleich flog eine Ente hin und biß es in den Nacken.

»Laß es in Ruhe!« sagte die Mutter. »Es thut ja niemand etwas.«

»Ja, aber es ist so groß und ungewöhnlich,« sagte die beißende Ente, »und deshalb muß es gepufft werden.«

»Es sind hübsche Kinder, welche die Mutter hat,« sagte die Ente mit dem Lappen um das Bein. »Alle zusammen schön, bis auf das eine, das ist nicht geglückt; ich möchte wünschen, daß sie es umarbeiten könnte.«

»Das geht nicht, Ihro Gnaden,« sagte die Entleinmutter; »es ist nicht hübsch, aber es hat ein gutes Gemüt und schwimmt so herrlich wie eins von den andern, ja, ich darf sagen, noch etwas besser; ich denke, es wird hübsch heranwachsen und mit der Zeit etwas kleiner werden; es hat so lange in dem Ei gelegen und deshalb nicht die rechte Gestalt bekommen!« Und so zupfte sie es im Nacken und glättete das Gefieder. »Es ist überdies ein Enterich,« sagte sie, »und darum macht es nicht so viel aus. Ich denke, er wird gute Kräfte bekommen, er schlägt sich schon durch.«

»Die andern Entlein sind niedlich,« sagte die Alte. »Thut nun, als ob Ihr zu Hause wäret, und findet Ihr einen Aalkopf, so könnt Ihr mir ihn bringen.«

Und so waren sie wie zu Hause.

Aber das arme Entlein, welches zuletzt aus dem Ei[100] gekrochen war und so häßlich aussah, wurde gebissen, gestoßen und zum besten gehalten, und das sowohl von den Enten wie von den Hühnern. »Es ist zu groß,« sagten sie allesamt, und der kalekutische Hahn, welcher mit Sporen zur Welt gekommen war und deshalb glaubte, daß er Kaiser sei, blies sich wie ein Fahrzeug mit vollen Segeln auf, ging gerade auf dasselbe los, und dann kollerte er und wurde ganz rot am Kopfe. Das arme Entlein wußte weder, wo es stehen noch gehen sollte; es war betrübt, weil es häßlich aussah und vom ganzen Entenhofe verspottet wurde.

So ging es den ersten Tag, und später wurde es schlimmer und schlimmer. Das Entlein wurde von allen gejagt, selbst seine Geschwister waren böse gegen dasselbe und sagten immer: »Wenn die Katze Dich nur fangen möchte, Du häßliches Geschöpf!« und die Mutter sagte: »Wenn Du nur weit fort wärest!« Die Enten bissen es, und die Hühner schlugen es, und das Mädchen, welches die Tiere füttern sollte, stieß mit dem Fuße danach.

Da lief und flog es über das Gehege; die kleinen Vögel in den Büschen flogen erschrocken auf. »Das geschieht, weil ich häßlich bin!« dachte das Entlein und schloß die Augen, lief aber gleichwohl weiter; so kam es hinaus zu dem großen Moor, wo die wilden Enten wohnten. Hier lag es die ganze Nacht, es war sehr müde und kummervoll.

Am Morgen flogen die wilden Enten auf und sie betrachteten den neuen Kameraden. »Was bist Du für einer?« fragten sie, und das Entlein wandte sich nach allen Seiten und grüßte, so gut es konnte.

»Du bist außerordentlich häßlich!« sagten die wilden Enten. »Aber das kann uns gleichgiltig sein, wenn Du Dich nur nicht in unsere Familie hinein heiratest.« Das Arme dachte wahrlich nicht daran, sich zu verheiraten, wenn es nur die Erlaubnis hatte, im Schilfe zu liegen und etwas Moorwasser zu trinken.[101]

So lag es ganze zwei Tage. Da kamen zwei wilde Gänse oder richtiger wilde Gänseriche dorthin; es war noch nicht lange her, daß sie aus dem Ei gekrochen waren, und deshalb waren es auch so keck.

»Höre, Kamerad,« sagten sie, »Du bist so häßlich, daß wir Dich gut leiden mögen; willst Du mitziehen und Zugvogel sein? Hier nahebei in einem andern Moor giebt es einige liebliche, wilde Gänse, alle zusammen Fräulein, die da Rapp! sagen können. Du bist im stande, Dein Glück zu machen, so häßlich Du auch bist!«

»Piff, paff!« ertönte es und beide wilde Gänseriche fielen tot in das Schilf nieder, und das Wasser wurde blutrot. »Piff, paff!« erscholl es wieder, und ganze Scharen wilder Gänse flogen aus dem Schilfe auf, und dann knallte es wieder. Es war große Jagd; die Jäger lagen rings um das Rohr herum, ja einige saßen oben in den Baumzweigen, welche sich weit über das Schilf hinstreckten, der blaue Dampf zog gleich Wolken in die dunklen Bäume hinein und ging weit über das Wasser hin; zum Moor kamen die Jagdhunde: platsch! platsch! – das Schilf und Rohr neigte sich nach allen Seiten. Das war ein Schreck für das arme Entlein; es wendete den Kopf, um ihn unter den Flügel zu stecken, und im selben Augenblick stand ein fürchterlich großer Hund dicht bei dem Entlein, die Zunge hing ihm lang aus dem Halse heraus, und die Augen leuchteten greulich häßlich; er streckte seinen Rachen dem Entlein gerade entgegen, zeigte ihm die scharfen Zähne und – platsch! platsch! ging er wieder, ohne es zu packen.

»O, Gott sei Dank!« seufzte das Entlein, »ich bin so häßlich, daß mich selbst der Hund nicht beißen mag!«

So lag es ganz still, während der Bleihagel durch das Schilf sauste und Schuß auf Schuß knallte.

Erst spät am Tage wurde es still, aber das arme Junge wagte noch nicht, sich zu erheben; es wartete noch mehrere Stunden, bevor es sich umsah, und dann eilte es fort aus dem[102] Moor, so schnell es konnte; es lief über Feld und Wiese, und es war ein Sturm, daß es ihm schwer wurde, von der Stelle zu kommen.

Gegen Abend erreichte es eine kleine Bauernhütte, die war so baufällig, daß sie selbst nicht wußte, nach welcher Seite sie fallen wollte und darum blieb sie stehen. Der Sturm umsauste das Entlein so, daß es sich niedersetzen mußte, um sich dagegen zu stemmen; und es wurde schlimmer und schlimmer; da bemerkte es, daß die Thür aus der einen Angel gegangen war, und so schief hing, daß es durch die Öffnung in die Stube hinein schlüpfen konnte, und das that es.

Hier wohnte eine alte Frau mit ihrer Katze und ihrem Huhne, und die Katze, welche sie Söhnchen nannte, konnte einen Buckel machen und spinnen, sie sprühte sogar Funken, aber dann mußte man sie gegen die Haare streicheln. Das Huhn hatte ganz kleine, niedrige Beine und deshalb wurde es Küchelchen-Kurzbein genannt; es legte gut Eier, und die Frau liebte es wie ihr eigenes Kind.

Am Morgen bemerkte man sogleich das fremde Entlein, und die Katze fing an zu spinnen und das Huhn zu glucken.[103]

»Was ist das?« sagte die Frau und sah sich rings um, aber sie sah nicht gut, und so glaubte sie, daß das Entlein eine fette Ente sei, die sich verirrt habe. »Das ist ja ein seltsamer Fang!« sagte sie. »Nun kann ich Enteneier bekommen. Wenn es nur kein Enterich ist! Das müssen wir erproben.«

Und so wurde das Entlein für drei Wochen auf Probe angenommen, aber da kamen keine Eier. Und die Katze war Herr im Hause und das Huhn war die Frau und immer sagten sie: »Wir und die Welt!« denn sie glaubten, daß sie die Hälfte seien, und zwar der allerbeste Teil. Das Entlein glaubte, daß man auch eine andere Meinung haben könne, aber das litt das Huhn nicht.

»Kannst Du Eier legen?« fragte es.

»Nein!«

»So wirst Du Deinen Mund halten!«

Und die Katze sagte: »Kannst Du einen krummen Buckel machen, spinnen und Funken sprühen?«

»Nein!«

»So darfst Du auch keine Meinung haben, wenn vernünftige Leute sprechen!«

Das Entlein saß im Winkel und war bei schlechter Laune; da fiel es ihm ein, an die frische Luft und den Sonnenschein zu denken; es bekam so sonderbare Lust, auf dem Wasser zu schwimmen, daß es nicht unterlassen konnte, dies der Henne zu sagen.

»Was fehlt Dir?« fragte diese. »Du hast nichts zu thun, deshalb bekommst Du die Grillen! Lege Eier oder spinne, so gehen sie vorüber.«

»Aber es ist so schön, auf dem Wasser zu schwimmen,« sagte das Entlein, »so herrlich, es über dem Kopfe zusammenschlagen zu lassen und auf den Grund niederzutauchen!«

»Ja, das ist ein großes Vergnügen!« sagte die Henne. »Du bist wohl verrückt geworden! Frage die Katze danach, sie ist die klügste, die ich kenne, ob sie es liebt, auf dem Wasser[104] zu schwimmen oder unterzutauchen; ich will nicht von mir sprechen. Frage selbst unsere Herrschaft, die alte Frau, klüger als sie ist niemand auf der Welt! Glaubst Du, daß sie Lust hat, zu schwimmen und das Wasser über dem Kopfe zusammenschlagen zu lassen?«

»Ihr versteht mich nicht!« sagte die Ente.

»Wir verstehen Dich nicht? Wer soll Dich denn verstehen können? Du wirst doch wohl nicht klüger sein wollen als die Katze und die Frau, mich will ich nicht erwähnen! Bilde Dir nichts ein, Kind, und danke Deinem lieben Schöpfer für all' das Gute, das man Dir erwiesen! Bist Du nicht in eine warme Stube gekommen und hast einen Umgang, von dem Du etwas lernen kannst? Aber Du bist ein Schwätzer, und es ist nicht erfreulich, mit Dir umzugehen. Mir kannst Du glauben, ich meine es gut mit Dir, ich sage Dir Unannehmlichkeiten, und daran kann man seine wahren Freunde erkennen! Sieh zu, daß Du Eier legen oder spinnen und Funken sprühen lernst!«

»Ich glaube, ich gehe hinaus in die weite Welt!« sagte das Entlein.

»Ja, thue das!« sagte das Huhn.

Und so ging das Entlein; es schwamm auf dem Wasser, es tauchte unter, aber von allen Tieren wurde es wegen seiner Häßlichkeit übersehen.

Nun trat der Herbst ein, die Blätter im Walde wurden gelb und braun, der Wind riß sie ab, sodaß sie umhertanzten, und oben in der Luft war es sehr kalt; die Wolken hingen schwer von Hagel und Schneeflocken, und auf dem Zaun stand ein Rabe und schrie: »Au, au!« vor lauter Kälte; ja, man konnte ordentlich frieren, wenn man daran dachte. Das arme Entlein hatte es wahrlich nicht gut. Eines Abends, als die Sonne schön unterging, kam ein ganzer Schwarm herrlicher, großer Vögel aus dem Busche; das Entlein hatte solche nie so schön gesehen. Sie waren ganz blendend weiß, mit langen,[105] geschmeidigen Hälsen, es waren Schwäne. Sie stießen einen ganz eigentümlichen Ton aus, breiteten ihre prächtigen, langen Flügel aus und flogen von der kalten Gegend fort nach warmen Ländern, nach offenen Seen. Sie stiegen sehr hoch, und dem häßlichen, kleinen Entlein wurde es sonderbar zu Mute; es drehte sich im Wasser wie ein Rad rund herum, streckte den Hals hoch in die Luft nach ihnen aus und stieß einen so lauten und sonderbaren Schrei aus, daß es sich selbst davor fürchtete. O, es konnte die schönen, die glücklichen Vögel nicht vergessen, und sobald es sie nicht mehr erblickte, tauchte es gerade bis auf den Grund, und als es wieder heraufkam, war es gerade wie außer sich. Es wußte nicht, wie die Vögel hießen, nicht, wohin sie flogen, aber doch war es ihnen gut, wie es nie jemand gewesen. Es beneidete sie durchaus nicht; wie konnte es ihm einfallen, sich solche Lieblichkeit zu wünschen! Es wäre schon froh gewesen, wenn die Enten es unter sich geduldet hätten, das arme, häßliche Tier!

Der Winter wurde immer kälter; das Entlein mußte im Wasser herumschwimmen, um das völlige Zufrieren desselben zu verhindern; aber in der Nacht wurde das Loch, worin es schwamm, kleiner und kleiner; es fror, sodaß es in der Eisdecke knackte; das Entlein mußte fortwährend die Beine gebrauchen, damit[106] das Wasser sich nicht schloß; zuletzt wurde es matt, lag ganz still und fror so im Eise fest.

Des Morgens früh kam ein Landmann, der dies sah; er ging hin und schlug mit seinem Holzschuh das Eis in Stücke und trug das Entlein heim zu seiner Frau. Da wurde es wieder belebt.

Die Kinder wollten mit demselben spielen, aber das Entlein glaubte, sie wollten ihm etwas zu Leide thun, und fuhr in der Angst gerade in den Milchnapf hinein, sodaß die Milch in die Stube hinausspritzte; die Frau schrie, schlug die Hände zusammen, worauf es in das Butterfaß, dann hinunter in die Milchtonne und dann wieder aufflog. Wie sah es da aus! Die Frau schrie und schlug mit der Feuerzange darnach, die Kinder rannten einander über den Haufen, um das Entlein zu fangen; sie lachten und schrieen! Gut war es, daß die Thür aufstand und es zwischen die Reiser in den frischgefallenen Schnee schlüpfen konnte; da lag es, ganz ermattet.

Aber all' die Not und das Elend, welches das Entlein in dem harten Winter erdulden mußte, zu erzählen, würde zu trübe sein. Es lag im Moor, zwischen dem Rohre, als die Sonne wieder warm zu scheinen begann; die Lerchen sangen, es war herrlicher Frühling.

Da konnte auf einmal das Entlein seine Flügel schwingen, sie brausten stärker als früher und trugen es kräftig davon; und ehe dasselbe es recht wußte, befand es sich in einem großen Garten, wo die Äpfelbäume in Blüte standen, wo der Flieder duftete und seine langen, grünen Zweige gerade bis zu den gekrümmten Kanälen hinunter neigte. O, hier war es schön und frühlingsfrisch! Gerade vorn aus dem Dickicht kamen drei prächtige weiße Schwäne; sie brausten mit den Federn und schwammen leicht auf dem Wasser. Das Entlein kannte die prächtigen Tiere und wurde von einer eigentümlichen Traurigkeit befallen.

»Ich will zu ihnen hinfliegen, zu den königlichen Vögeln, und sie werden mich totschlagen, weil ich, da ich so häßlich bin,[107] mich ihnen zu nähern wage; aber das ist ja gleichviel! Besser, von ihnen getötet, als von den Enten gezwackt, von den Hühnern geschlagen, von dem Mädchen, welches den Hühnerhof hütet, gestoßen zu werden und im Winter Mangel zu leiden.« Es flog hinaus in das Wasser und schwamm den prächtigen Schwänen entgegen; diese erblickten es und schossen mit brausenden Federn auf dasselbe los. »Tötet mich nur!« sagte das arme Tier und neigte seinen Kopf der Wasserfläche zu und erwartete den Tod. Aber was erblickte es in dem klaren Wasser? Es sah sein eigenes Bild unter sich, das kein plumper, schwarzgrauer Vogel mehr, häßlich und garstig, sondern selbst ein Schwan war.

Es schadet nichts, in einem Entenhofe geboren zu sein, wenn man nur in einem Schwanenei gelegen hat.

Es fühlte sich ordentlich erfreut über all' die Not und die Drangsal, welche es erduldet; nun erkannte es erst sein Glück an all' der Herrlichkeit, die es begrüßte.

Die großen Schwäne umschwammen es und streichelten es mit dem Schnabel.

Im Garten kamen da einige kleine Kinder, die warfen Brot und Korn in das Wasser, und das kleinste rief: »Da ist[108] ein neuer!« Und die anderen Kinder jubelten mit: »Ja, es ist ein neuer angekommen!« Sie klatschten mit den Händen und tanzten umher, liefen zum Vater und zu der Mutter, und es wurde Brot und Kuchen in das Wasser geworfen, und sie sagten alle: »Der neue ist der schönste, so jung und so prächtig!« Und die alten Schwäne neigten sich vor ihm.

Da fühlte er sich beschämt und steckte den Kopf unter seine Flügel; er wußte selbst nicht, was er beginnen sollte, er war allzu glücklich, aber durchaus nicht stolz; denn ein gutes Herz wird nie stolz! Er dachte daran, wie er verfolgt und verhöhnt worden war, und hörte nun alle sagen, daß er der schönste aller schönen Vögel sei; selbst der Flieder bog sich mit den Zweigen gerade zu ihm in das Wasser hinunter, und die Sonne schien warm und mild. Da brausten seine Federn, der schlanke Hals hob sich und aus vollem Herzen jubelte er: »So viel Glück habe ich mir nicht träumen lassen, als ich noch das häßliche Entlein war!«


## Nächste Station
```{r, echo=FALSE}
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=13.46537, lat=52.55321, popup="Station 6 der Schnitzeljagd für Familien am Weißen See")
```


:::

